# MediaMan configuration file
#
# NOTE: This file is for PUBLIC DATA ONLY!

# Drive
GOOGLE_CLIENT_SECRETS: "credentials/drive/client-secrets/client-secret.json"
GOOGLE_CREDENTIALS: "credentials/drive/credentials/stored"
GOOGLE_DESTINATION: "MediaMan"

# Local
LOCAL_DESTINATION: "mediaman"
