# MediaMan configuration file
#
# NOTE: This file is for PUBLIC DATA ONLY!


### Fields:
# - type: <choose one>
# - quota: <e.g. 100GB>
# - destination: <path, folder name, URI, etc.>
# - credentials: <nested values, arbitrary>
# - cost: <true/false.  Whether this service costs money for upload/download/storage.  Defaults to false.>


### Required Fields:
# type, quota, destination


### Service Types:
# - folder
# - dropbox
# - google drive
# - aws s3
# - aws glacier


# service configs
services:
  drive:
    type: google drive
    quota: 180GB
    destination: MediaMan
    extra:
      GOOGLE_CLIENT_SECRETS: credentials/drive/client-secrets/client-secret.json
      GOOGLE_CREDENTIALS: credentials/drive/credentials/stored
  local:
    type: folder
    quota: 20GB
    destination: /Users/mattcotton/MediaMan
  128a:
    type: folder
    quota: 127GB
    destination: /Volumes/128GB-alpha/MediaMan
  128b:
    type: folder
    quota: 127GB
    destination: /Volumes/128GB-beta/MediaMan
  64a:
    type: folder
    quota: 63GB
    destination: /Volumes/64GB-alpha/MediaMan
  64b:
    type: folder
    quota: 63GB
    destination: /Volumes/64GB-beta/MediaMan
  64c:
    type: folder
    quota: 63GB
    destination: /Volumes/64GB-gamma/MediaMan
  64d:
    type: folder
    quota: 63GB
    destination: /Volumes/64GB-delta/MediaMan
  # s3:
  #   type: aws s3
  #   quota: 10GB
  #   destination: MediaMan
  #   cost: true
  # ex:
  #   type: folder
  #   quota: 1TB
  #   destination: /Volumes/ExternalDrive/me
  # net:
  #   type: folder
  #   quota: 2TB
  #   destination: /Network/some-share/me

resolution-order:
  - local
  - ex
  - net
  - drive
  - s3

strategy:
  keep-copies: 2
  prefer-grouping:
    video:
      - ex
      - net
    music:
      - drive
      - ex
      - net
